### ISSUE TITLE
how to use this, thank you 

### ISSUE THREAD

**Issue by ghost** [alencarrh/unisinos-java2python#1]
I don't know the Java language. How do I use this 

thank you  very much

**Comment by alencarrh** [comment]
Hi @find456789 

No problem, I can explain :)

Before anything, just let me tell you that this was a college assignment, so it doesn't follow any good practice nor good way of implementation things. It doesn't work really well yet.  At some point I'll take some time to properly implement this translator and do a README for it .

But, answering you question:
This is a simple java project with maven.

I suggest you to use any IDE for Java because its going to make it simple to compile and execute the program (Intellij, Eclipse, Netbeans or any other you like). 
But, if you want to execute it manually, you can do it by following this steps:

#### pre requirements
* **Maven 3** *[how to install](https://www.mkyong.com/maven/how-to-install-maven-in-windows/)*
* **Java 8**
* **[Lombok](https://projectlombok.org/)** Enabled in your IDE (*only if you use an IDE*)

### initial setup
```bash
git clone https://github.com/alencarrh/unisinos-java2python.git
cd unisinos-java2python
```

### building the project
this step will create a `.jar` inside target folder (only use/consider the one with **spring-boot** in the name. this project doesn't have anything of Spring in it, only the library to create the .jar)
```bash
mvn clean install
```

### executing
```bash
java -jar target/java2python-1.0-spring-boot.jar "src/main/java/unisinos/tradutores/java2python/exemplos/WhileExemplo.java"
```
input exapmle:
```java
package unisinos.tradutores.java2python.exemplos;

public class WhileExemplo {

    public void metodo1(int a, int b) {

        while (a < b) {
            System.out.println(b);

            a++;
        }

    }

    public void metodo2() {
        int i = 0;
        while (i < 10) {
            int j = 0;
            while (j < 10) {
                System.out.println(i+j);
            }
        }
    }

}
```
output example:
```python3
class WhileExemplo:

    def metodo1(self,a = None, b = None): # returns VOID

        while (a<b):
            print(b)
            a += 1

    def metodo2(self): # returns VOID
        i = 0

        while (i<10):
            j = 0

            while (j<10):
                print(i+j)
```


Everything 'till here is about how to execute. I'll simple explain about the code itself now.

This implementation to translate a Java code to Python code is using the [ANTLR](https://www.antlr.org/) (ANother Tool for Language Recognition) and my code over the code that ANTLR creates.
If you look a little bit into the ANTLR I think you'll be able to understand a little my code. But the ideia is that the ANTLR will create a few classes based in a language grammar, in this case, the [grammar of Java 8](https://github.com/alencarrh/unisinos-java2python/blob/master/src/main/java/unisinos/tradutores/java2python/gramatica/Java8.g4). The ANTLR works/has two ways of classes. The Listener and the Visitor. This code uses the Listener class.

**Comment by ghost** [comment]
@alencarrh 
thank you very much  :)
